In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score

In [75]:
#Load the dataset from csv file using Pandas
data = pd.read_csv("C:/Data Science/creditcard.csv")

In [76]:
#We will take just fraction of data and set random state as 1 so that it does not change
#data = data.sample(frac=.10,random_state=1)
#print(data.shape)

In [77]:
y = data['Class']

In [78]:
X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.2)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(227845, 31) (227845,)
(56962, 31) (56962,)


In [79]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)


In [80]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


0.9990519995786665
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     56863
          1       0.78      0.64      0.70        99

avg / total       1.00      1.00      1.00     56962

[[56845    18]
 [   36    63]]


In [81]:
#Apply SMOTE To improve Precision and Recall
y_train.value_counts()

0    227452
1       393
Name: Class, dtype: int64

In [82]:
smt = SMOTE()
X_train, y_train = smt.fit_sample(X_train, y_train)

In [83]:
np.bincount(y_train)

array([227452, 227452], dtype=int64)

In [84]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)


In [85]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.982567325585478
             precision    recall  f1-score   support

          0       1.00      0.98      0.99     56863
          1       0.08      0.89      0.15        99

avg / total       1.00      0.98      0.99     56962

[[55881   982]
 [   11    88]]


In [86]:
from imblearn.under_sampling import NearMiss

In [87]:
nr = NearMiss()
X_train, y_train = nr.fit_sample(X_train, y_train)

In [88]:
np.bincount(y_train)

array([227452, 227452], dtype=int64)

In [89]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [90]:
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.982567325585478
             precision    recall  f1-score   support

          0       1.00      0.98      0.99     56863
          1       0.08      0.89      0.15        99

avg / total       1.00      0.98      0.99     56962

[[55881   982]
 [   11    88]]
